[tool.black]
line-length = 120
target-version = ["py310"]

# todo: disable later
skip-string-normalization = true
exclude = '/(\.eggs|\.git|\.hg|\.mypy_cache|\.nox|\.tox|\.venv|\.svn|_build|buck-out|build|dist|migrations|migrations)/'

[tool.isort]
combine_as_imports = true
order_by_type = true
include_trailing_comma = true
use_parentheses = true
multi_line_output = 3
src_paths = ['tickets']
